#!/bin/bash
# Check branch name: feature/xxx, bugfix/xxx, hotfix/xxx, release/xxx
branch_name=$(git symbolic-ref --short HEAD)
regex="^(feature|bugfix|hotfix|release|develop)(\/[a-z0-9\-_]+)?$"
if ! echo "$branch_name" | grep -qE "$regex"; then
    echo "Error: branch name '$branch_name' does not match the required pattern."
    echo "Please use: feature/xxx, bugfix/xxx, hotfix/xxx, release/xxx"
    exit 1
fi
